<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../shared/shared.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../vpnctl.core/vpnctl.core.csproj"/>
  </ItemGroup>

</Project>
